# permissions for end users to edit monitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: monitor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-deploy-monitor
    app.kubernetes.io/part-of: k8s-deploy-monitor
    app.kubernetes.io/managed-by: kustomize
  name: monitor-editor-role
rules:
- apiGroups:
  - deploy.deploy-monitor.local
  resources:
  - monitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.deploy-monitor.local
  resources:
  - monitors/status
  verbs:
  - get
