apiVersion: deploy.deploy-monitor.local/v1alpha1
kind: Monitor
metadata:
  name: monitor-config
  namespace: default
spec:
  podEndpoint: "https://your-webhook-endpoint-here"
  deploymentEndpoint: "https://your-webhook-endpoint-here"
  apiKey: "your-api-key-here"
  apiKeyHeader: "Api-Key"
